Implement docksrv Makefile
src-d/docsrv pull request #20
Opened 2017-06-05 18:48 UTC by dpordomingo

After this PR is accepted, this project will implement docsrv Makefile

2017-06-06 08:28 UTC, Serabe commented
![1qdtcp](https://cloud.githubusercontent.com/assets/36221/26820344/d295f832-4aa2-11e7-951f-8755996fd3e8.jpg)

2017-06-06 08:28 UTC, Serabe approved these changes

2017-06-07 07:39 UTC, erizocosmico requested changes
Are we going to add docsrv'd docs to this project? Is it even going to be displayed in the landing?

2017-06-07 07:39 UTC, erizocosmico commented on Makefile
> +goBuild := CGO_ENABLED=0 go build -o
s/goBuild/go_build/

2017-06-07 09:33 UTC, dpordomingo commented
@erizocosmico I amended the PR unique commit with your suggestion  `s/goBuild/go_build/`
Answering your question about if this project will implement `docsrv` requirements, I'd say that all src-d public repositories should implement it (as said in the meeting for "defining our documentation")

2017-06-07 10:50 UTC, erizocosmico commented
But if they're not going to be displayed in source{d}'s landing what's the point of documenting the projects in a way that they can be?

2017-06-07 12:05 UTC, smola commented on Makefile
> +	@$(go_build) bin/docsrv docsrv.go
Maybe these should go without `@` so the command is outputted to the terminal?

2017-06-07 12:27 UTC, dpordomingo commented on Makefile
> +	@$(go_build) bin/docsrv docsrv.go
I'll do it, thanks

2017-06-07 12:31 UTC, dpordomingo commented
@smola I removed the `@` from the `@$(go_build) bin/docsrv docsrv.go` command (and amended that change over the prev commit)
@erizocosmico it seems that all projects will appear in the landing

2017-07-18 14:39 UTC, erizocosmico commented
You need to rebase

2017-07-18 14:49 UTC, dpordomingo commented
@erizocosmico done

2017-07-18 14:50 UTC, merged